---
- name: Set Ip Loobpack
  hosts: all
  gather_facts: no

  tasks:
    - name: Set loopback IPv4 address
      ios_l3_interface:
        name: loopback 1
        ipv4: 10.0.1.1/24
        name: lo2
        ipv4: 10.0.1.2/30
        name: lo3
        ipv4: 10.0.0.1.3/30
    - name: Set loopback IPv6 address
       ios_l3_interface:
         name: lo6
         ipv6: 2001:db8:10::3/64
    - name: Set Ethernet0/1 IPv4 address
      ios_l3_interface:
        name: Ethernet0/2
        ipv4: 192.168.12.2/24
        name: Ethernet0/0
        ipv4: 192.168.100.2/25
        satte: shut
    - name: no shut
      ios_interface:
        name: Ethernet0/2
        state: present
        
    - name: Show ip
      ios_command:
        commands:
          - show ip int brief
      register: show_ip

    - debug: var=show_ip.stdout_lines
